spring:
  application:
    name: TGGoods
  datasource:
    url: jdbc:postgresql://localhost:5432/TgGoodsDB
    username: AdminTGGoodsDB
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/TgGoodsDB
    user: AdminTGGoodsDB
    password: root
    driver-class-name: org.postgresql.Driver
    schemas: tg_goods
    locations: db/migration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8642